package bookmark

import (
	"context"

	"github.com/HadesHo3820/ebvn-golang-course/internal/model"
)

// CreateBookmark implements the business logic for creating a new bookmark.
// The bookmark code is auto-generated by the database using an auto-increment
// sequence, eliminating the need for random code generation and collision handling.
//
// Parameters:
//   - ctx: Context for the operation
//   - description: User-provided description
//   - url: The target URL to shorten
//   - userID: The ID of the owner
//
// Returns:
//   - *model.Bookmark: The created bookmark with generated ID and auto-incremented code
//   - error: Any error during persistence
func (s *BookmarkSvc) CreateBookmark(ctx context.Context, description, url, userID string) (*model.Bookmark, error) {
	bookmark := &model.Bookmark{
		Description: description,
		URL:         url,
		UserID:      userID,
		// Code is auto-incremented by the database (PostgreSQL sequence)
	}

	bookmarkModel, err := s.repo.CreateBookmark(ctx, bookmark)
	if err != nil {
		return nil, err
	}

	return bookmarkModel, nil
}
