// Package handler provides HTTP handlers for the bookmark service API.
// This file contains the URL shortening handler which generates short codes for URLs.
package handler

import (
	"errors"
	"net/http"
	"strings"

	"github.com/HadesHo3820/ebvn-golang-course/internal/service"
	"github.com/gin-gonic/gin"
	"github.com/rs/zerolog/log"
)

// urlShortenRequest represents the JSON request body for URL shortening.
// It contains the original URL to shorten and an optional expiration time.
type urlShortenRequest struct {
	// Url is the original URL to be shortened.
	// binding:"required" makes sure this field is present
	// binding:"url" validates that the string is a valid URL format
	Url string `json:"url" binding:"required,url" example:"https://google.com"`
	// Exp is the optional expiration time in seconds for the shortened URL.
	// binding:"gte=0" ensures the expiration time is greater than or equal to 0
	Exp int `json:"exp" binding:"required,gte=0,lte=604800" example:"86400"`
}

// urlShortenResponse represents the JSON response for a successful URL shortening.
type urlShortenResponse struct {
	// Message indicates the status of the operation.
	Message string `json:"message" example:"Shorten URL generated successfully!"`
	// Code is the generated short code that maps to the original URL.
	Code string `json:"code" example:"string"`
}

// urlShortenHandler is the concrete implementation of the UrlShorten interface.
// It holds a reference to the URL shortening service.
type urlShortenHandler struct {
	urlService service.ShortenUrl
}

// UrlShorten defines the interface for URL shortening HTTP handlers.
// This interface allows for dependency injection and easier testing.
type UrlShorten interface {
	// ShortenUrl handles HTTP requests to shorten a URL.
	ShortenUrl(c *gin.Context)

	// GetUrl handles HTTP requests to retrieve the original URL for a short code.
	// It extracts the code from the URL path and redirects to the original URL.
	GetUrl(c *gin.Context)
}

// NewUrlShorten creates a new UrlShorten handler with the provided service dependency.
// It follows the constructor injection pattern for dependency management.
//
// Parameters:
//   - svc: The URL shortening service that provides the business logic.
//
// Returns:
//   - UrlShorten: An interface implementation that handles URL shortening HTTP requests.
func NewUrlShorten(svc service.ShortenUrl) UrlShorten {
	return &urlShortenHandler{
		urlService: svc,
	}
}

// @Summary Shorten URL
// @Description Generate a short code for the provided URL
// @Tags URL
// @Accept json
// @Produce json
// @Param request body urlShortenRequest true "URL shorten request"
// @Success 200 {object} urlShortenResponse
// @Failure 400 {object} map[string]string "Bad Request - invalid URL or validation error"
// @Failure 500 {object} map[string]string "Internal Server Error"
// @Router /v1/links/shorten [post]
func (h *urlShortenHandler) ShortenUrl(c *gin.Context) {
	var req urlShortenRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "wrong input"})
		return
	}

	code, err := h.urlService.ShortenUrl(c, req.Url, req.Exp)
	if err != nil {
		// Log the error using Zerolog's structured logging:
		// - .Str("url", ...): key-value pair for context
		// - .Err(err): standard error field
		// - .Msg(...): final message and write action
		log.Error().Str("url", req.Url).Err(err).Msg("Failed to shorten URL")
		c.JSON(http.StatusInternalServerError, gin.H{"message": "internal server error"})
		return
	}

	c.JSON(http.StatusOK, urlShortenResponse{
		Message: "Shorten URL generated successfully!",
		Code:    code,
	})
}

// GetUrl handles HTTP GET requests to retrieve and redirect to the original URL.
// It extracts the short code from the URL path, validates it, queries the service
// layer for the original URL, and redirects the client using HTTP 302 Found.
//
// Path Parameters:
//   - code: The 7-character alphanumeric short code generated by ShortenUrl.
//
// Responses:
//   - 302 Found: Redirects to the original URL.
//   - 400 Bad Request: Code is empty, malformed, or does not exist.
//   - 500 Internal Server Error: Database or service layer failure.
//
// @Summary Redirect to original URL
// @Description Retrieve the original URL for a short code and redirect the client
// @Tags URL
// @Param code path string true "Short code" example(abc1234)
// @Success 302 "Redirects to the original URL"
// @Failure 400 {object} map[string]string "Bad Request - wrong format"
// @Failure 500 {object} map[string]string "Internal Server Error"
// @Router /v1/links/{code} [get]
func (h *urlShortenHandler) GetUrl(c *gin.Context) {
	// Extract the short code from the URL path parameter.
	// The route is defined as /v1/links/:code, so Gin parses the dynamic segment.
	// Note: Gin may include leading/trailing slashes (e.g., "/abc1234/") for requests like /v1/links/abc1234/
	code := c.Param("code")

	// Trim any leading/trailing slashes that Gin might include from the URL path.
	code = strings.Trim(code, "/")

	if code == "" {
		c.JSON(http.StatusBadRequest, gin.H{"message": "wrong format"})
		return
	}
	// Query the service layer to retrieve the original URL for this code.
	url, err := h.urlService.GetUrl(c, code)
	if err != nil {
		// Check if the error is specifically "code not found" using sentinel error comparison.
		// This allows us to return a 400 Bad Request instead of a generic 500 error.
		if errors.Is(err, service.ErrCodeNotFound) {
			c.JSON(http.StatusBadRequest, gin.H{"message": "url not found"})
			return
		}

		// For any other errors (e.g., database connection issues), return 500.
		log.Error().
			Str("code", code).
			Err(err).
			Msg("Failed to retrieve URL for short code")
		c.JSON(http.StatusInternalServerError, gin.H{"message": "internal server error"})
		return
	}

	// Redirect the client to the original URL using HTTP 302 (Found).
	// This is the standard behavior for URL shorteners.
	c.Redirect(http.StatusFound, url)
}
