// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/HadesHo3820/ebvn-golang-course/internal/model"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/HadesHo3820/ebvn-golang-course/pkg/pagination"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateBookmark provides a mock function with given fields: ctx, description, url, userID
func (_m *Service) CreateBookmark(ctx context.Context, description string, url string, userID string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, description, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookmark")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.Bookmark, error)); ok {
		return rf(ctx, description, url, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Bookmark); ok {
		r0 = rf(ctx, description, url, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, description, url, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBookmark provides a mock function with given fields: ctx, bookmarkID, userID
func (_m *Service) DeleteBookmark(ctx context.Context, bookmarkID string, userID string) error {
	ret := _m.Called(ctx, bookmarkID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, bookmarkID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookmarks provides a mock function with given fields: ctx, userID, req
func (_m *Service) GetBookmarks(ctx context.Context, userID string, req *pagination.Request) (*pagination.Response[*model.Bookmark], error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarks")
	}

	var r0 *pagination.Response[*model.Bookmark]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *pagination.Request) (*pagination.Response[*model.Bookmark], error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *pagination.Request) *pagination.Response[*model.Bookmark]); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagination.Response[*model.Bookmark])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *pagination.Request) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBookmark provides a mock function with given fields: ctx, bookmarkID, userID, description, url
func (_m *Service) UpdateBookmark(ctx context.Context, bookmarkID string, userID string, description string, url string) error {
	ret := _m.Called(ctx, bookmarkID, userID, description, url)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, bookmarkID, userID, description, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
