// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/gen-pass": {
            "get": {
                "description": "Generates a cryptographically secure random password",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "password"
                ],
                "summary": "Generate a random password",
                "responses": {
                    "200": {
                        "description": "Generated password",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/health-check": {
            "get": {
                "description": "Health check",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health_check"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.healthCheckResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable - dependency unhealthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/links/shorten": {
            "post": {
                "description": "Generate a short code for the provided URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "URL"
                ],
                "summary": "Shorten URL",
                "parameters": [
                    {
                        "description": "URL shorten request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.urlShortenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.urlShortenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - invalid URL or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/links/{code}": {
            "get": {
                "description": "Retrieve the original URL for a short code and redirect the client",
                "tags": [
                    "URL"
                ],
                "summary": "Redirect to original URL",
                "parameters": [
                    {
                        "type": "string",
                        "example": "abc1234",
                        "description": "Short code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirects to the original URL"
                    },
                    "400": {
                        "description": "Bad Request - wrong format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handler.healthCheckResponse": {
            "type": "object",
            "properties": {
                "instance_id": {
                    "type": "string",
                    "example": "instance-123"
                },
                "message": {
                    "type": "string",
                    "example": "OK"
                },
                "service_name": {
                    "type": "string",
                    "example": "bookmark_service"
                }
            }
        },
        "internal_handler.urlShortenRequest": {
            "type": "object",
            "required": [
                "exp",
                "url"
            ],
            "properties": {
                "exp": {
                    "description": "Exp is the optional expiration time in seconds for the shortened URL.\nbinding:\"gte=0\" ensures the expiration time is greater than or equal to 0",
                    "type": "integer",
                    "maximum": 604800,
                    "minimum": 0,
                    "example": 86400
                },
                "url": {
                    "description": "Url is the original URL to be shortened.\nbinding:\"required\" makes sure this field is present\nbinding:\"url\" validates that the string is a valid URL format",
                    "type": "string",
                    "example": "https://google.com"
                }
            }
        },
        "internal_handler.urlShortenResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is the generated short code that maps to the original URL.",
                    "type": "string",
                    "example": "string"
                },
                "message": {
                    "description": "Message indicates the status of the operation.",
                    "type": "string",
                    "example": "Shorten URL generated successfully!"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EBVN Bookmark API",
	Description:      "A simple password generator API built with Go and Gin.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
