// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health-check": {
            "get": {
                "description": "Health check",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health_check"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-internal_handler_healthcheck_healthCheckData"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable - dependency unhealthy",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_healthcheck.pingErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/bookmarks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a paginated list of bookmarks for the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookmark"
                ],
                "summary": "List bookmarks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-array_github_com_HadesHo3820_ebvn-golang-course_internal_model_Bookmark"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new bookmark with a description and target URL. Returns the created bookmark with its short code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookmark"
                ],
                "summary": "Create a new bookmark",
                "parameters": [
                    {
                        "description": "Bookmark details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_bookmark.createBookmarkInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-github_com_HadesHo3820_ebvn-golang-course_internal_model_Bookmark"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            }
        },
        "/v1/bookmarks/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing bookmark's description and URL. Only the bookmark owner can update it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookmark"
                ],
                "summary": "Update a bookmark",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bookmark ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated bookmark details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_bookmark.updateBookmarkInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-any"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "404": {
                        "description": "Bookmark not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing bookmark. Only the bookmark owner can delete it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookmark"
                ],
                "summary": "Delete a bookmark",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bookmark ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-any"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "404": {
                        "description": "Bookmark not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            }
        },
        "/v1/gen-pass": {
            "get": {
                "description": "Generates a cryptographically secure random password",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "password"
                ],
                "summary": "Generate a random password",
                "responses": {
                    "200": {
                        "description": "Generated password",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            }
        },
        "/v1/links/shorten": {
            "post": {
                "description": "Generate a short code for the provided URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "URL"
                ],
                "summary": "Shorten URL",
                "parameters": [
                    {
                        "description": "URL shorten request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_url.urlShortenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            }
        },
        "/v1/links/{code}": {
            "get": {
                "description": "Retrieve the original URL for a short code and redirect the client",
                "tags": [
                    "URL"
                ],
                "summary": "Redirect to original URL",
                "parameters": [
                    {
                        "type": "string",
                        "example": "abc1234",
                        "description": "Short code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirects to the original URL"
                    },
                    "400": {
                        "description": "Bad Request - wrong format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            }
        },
        "/v1/self/info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the authenticated user's profile information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-github_com_HadesHo3820_ebvn-golang-course_internal_model_User"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing token",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the authenticated user's profile information (display name and/or email)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Update profile request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_user.updateSelfInfoReqBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Profile updated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-any"
                        }
                    },
                    "400": {
                        "description": "No data provided for update",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing token",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "404": {
                        "description": "User does not exist",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            }
        },
        "/v1/users/login": {
            "post": {
                "description": "Authenticate a user with username and password, returns a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login a user",
                "parameters": [
                    {
                        "description": "User login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_user.loginInputBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-string"
                        }
                    },
                    "400": {
                        "description": "Invalid username or password",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            }
        },
        "/v1/users/register": {
            "post": {
                "description": "Register a new user with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_user.registerInputBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-internal_handler_user_registerUserData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_HadesHo3820_ebvn-golang-course_internal_dto.Metadata": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer",
                    "example": 1
                },
                "first_page": {
                    "type": "integer",
                    "example": 1
                },
                "last_page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                },
                "total_records": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.Metadata"
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-array_github_com_HadesHo3820_ebvn-golang-course_internal_model_Bookmark": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_model.Bookmark"
                    }
                },
                "message": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.Metadata"
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-github_com_HadesHo3820_ebvn-golang-course_internal_model_Bookmark": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_model.Bookmark"
                },
                "message": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.Metadata"
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-github_com_HadesHo3820_ebvn-golang-course_internal_model_User": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_model.User"
                },
                "message": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.Metadata"
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-internal_handler_healthcheck_healthCheckData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_handler_healthcheck.healthCheckData"
                },
                "message": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.Metadata"
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-internal_handler_user_registerUserData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_handler_user.registerUserData"
                },
                "message": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.Metadata"
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_internal_dto.SuccessResponse-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_HadesHo3820_ebvn-golang-course_internal_dto.Metadata"
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_internal_model.Bookmark": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_internal_model.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_HadesHo3820_ebvn-golang-course_pkg_response.Message": {
            "type": "object",
            "properties": {
                "details": {
                    "description": "Details contains a list of specific error messages or additional information, if any.\nIf empty, this field is omitted from the JSON response."
                },
                "message": {
                    "description": "Message is a brief summary of the response (e.g., \"Input error\").",
                    "type": "string"
                }
            }
        },
        "internal_handler_bookmark.createBookmarkInput": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "description": {
                    "description": "Description of the bookmark",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Your description here"
                },
                "url": {
                    "description": "URL to be shortened",
                    "type": "string",
                    "maxLength": 2048,
                    "example": "https://example.com"
                }
            }
        },
        "internal_handler_bookmark.updateBookmarkInput": {
            "type": "object",
            "required": [
                "id",
                "url"
            ],
            "properties": {
                "description": {
                    "description": "Description of the bookmark",
                    "type": "string",
                    "maxLength": 255,
                    "example": "Google"
                },
                "id": {
                    "description": "ID is the bookmark identifier from the URL path",
                    "type": "string"
                },
                "url": {
                    "description": "URL to be shortened",
                    "type": "string",
                    "maxLength": 2048,
                    "example": "https://www.google.com"
                }
            }
        },
        "internal_handler_healthcheck.healthCheckData": {
            "type": "object",
            "properties": {
                "instance_id": {
                    "type": "string",
                    "example": "instance-123"
                },
                "service_name": {
                    "type": "string",
                    "example": "bookmark_service"
                }
            }
        },
        "internal_handler_healthcheck.pingErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "instance_id": {
                    "type": "string",
                    "example": "instance-123"
                },
                "message": {
                    "type": "string",
                    "example": "OK"
                },
                "service_name": {
                    "type": "string",
                    "example": "bookmark_service"
                }
            }
        },
        "internal_handler_url.urlShortenRequest": {
            "type": "object",
            "required": [
                "exp",
                "url"
            ],
            "properties": {
                "exp": {
                    "description": "Exp is the optional expiration time in seconds for the shortened URL.\nbinding:\"gte=0\" ensures the expiration time is greater than or equal to 0",
                    "type": "integer",
                    "maximum": 604800,
                    "minimum": 0,
                    "example": 86400
                },
                "url": {
                    "description": "Url is the original URL to be shortened.\nbinding:\"required\" makes sure this field is present\nbinding:\"url\" validates that the string is a valid URL format",
                    "type": "string",
                    "example": "https://google.com"
                }
            }
        },
        "internal_handler_user.loginInputBody": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Password is the user's password.",
                    "type": "string",
                    "minLength": 8
                },
                "username": {
                    "description": "Username is the user's login identifier.",
                    "type": "string"
                }
            }
        },
        "internal_handler_user.registerInputBody": {
            "type": "object",
            "required": [
                "display_name",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "display_name": {
                    "description": "DisplayName is the user's display name shown in the UI.",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "email": {
                    "description": "Email is the user's email address.",
                    "type": "string"
                },
                "password": {
                    "description": "Password must contain at least one uppercase, one lowercase, one digit, and one special character.",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 8
                },
                "username": {
                    "description": "Username is the unique login identifier for the user.",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2
                }
            }
        },
        "internal_handler_user.registerUserData": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handler_user.updateSelfInfoReqBody": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "description": "` + "`" + `validate:\"omitempty,email\"` + "`" + ` allow empty email (only validates format when a value is provided)",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your Bearer token in the format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.4",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EBVN Bookmark API",
	Description:      "A simple password generator API built with Go and Gin.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
